INSERT INTO competence 
VALUES ('A1.4.2', ""),
VALUES ('A1.4.3', ""),
VALUES ('A2.1.1', ""),
VALUES ('A2.1.2', ""),
VALUES ('A2.2.1', ""),
VALUES ('A2.2.2', ""),
VALUES ('A2.2.3', ""),
VALUES ('A2.3.1', ""),
VALUES ('A2.3.2', ""),
VALUES ('A3.2.1', ""),
VALUES ('A3.2.2', ""),
VALUES ('A4.1.1', ""),
VALUES ('A4.1.2', ""),
VALUES ('A4.1.3', ""),
VALUES ('A4.1.4', ""),
VALUES ('A4.1.5', ""),
VALUES ('A4.1.6', ""),
VALUES ('A4.1.7', ""),
VALUES ('A4.1.8', ""),
VALUES ('A4.1.9', ""),
VALUES ('A4.1.10', ""),
VALUES ('A4.2.1', "",
VALUES ('A4.2.2', ""),
VALUES ('A4.2.3', "Réalisation des tests nécessaires à la mise en production d'éléments mis à jour "),
VALUES ('A4.2.4', "Mise à jour d'une documentation technique "),
VALUES ('A5.1.1', "Mise en place d'une gestion de configuration"),
VALUES ('A5.1.2', "Recueil d'informations sur une configuration et ses éléments"),
VALUES ('A5.1.3', "Suivi d'une configuration et de ses éléments"),
VALUES ('A5.1.4', "Étude de propositions de contrat de service (client, fournisseur)"),
VALUES ('A5.1.5', "Évaluation d'un élément de configuration ou d'une configuration"),
VALUES ('A5.1.6', "Évaluation d'un investissement informatique"),
VALUES ('A5.2.2', "Exploitation des référentiels, normes et standards adoptés par le prestataire"),
VALUES ('A5.2.1', "Veille technologique"),
VALUES ('A5.2.3', "Repérage des compléments de formation ou d'auto-formation ... "),
VALUES ('A5.2.4', "Étude d˜une technologie, d'un composant, d'un outil ou d'une méthode  "),
